#!/bin/bash  


touch $1.cpp  
echo "#include <stdio.h>" >> $1.cpp  
echo "#include <stdlib.h>" >> $1.cpp  
echo -e "\n int main(void){" >> $1.cpp  
#-e 讓換行有動作  

echo "	printf("Hello World!");" >> $1.cpp  

echo "}" >> $1.cpp
